# Generated by Django 2.1 on 2018-08-18 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='dealer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='endpoints.Dealer'),
        ),
    ]
