# Generated by Django 2.1 on 2018-08-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_auto_20180818_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='searches',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.Visits'),
        ),
    ]
