# Generated by Django 2.1 on 2018-08-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_visits_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searches',
            name='value',
        ),
        migrations.AddField(
            model_name='searches',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='endpoints.Car'),
            preserve_default=False,
        ),
    ]
