# Generated by Django 2.1 on 2018-08-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0010_auto_20180823_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
